import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import { Bricolage_Grotesque } from "next/font/google";

const BingoDilan = localFont({
  src: "../public/fonts/BingoDilan-Regular.ttf",
  variable: "--font-bingo",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
export const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["600"], // SemiBold
  variable: "--font-bricolage",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["600"], // SemiBold
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${BingoDilan.variable} ${bricolage.variable}`}
    >
      <body className={`antialiased bg-black text-white`}>{children}</body>
    </html>
  );
}
